/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#a4c9ff',
        'inverse-primary': '#a4c9ff',
        primary: '#005da7',
        'on-surface': '#1b1c1c',
        'on-primary-fixed-variant': '#004883',
        secondary: '#496080',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        tertiary: '#7f5300',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001c39',
        'on-primary-container': '#fdfcff',
        'on-tertiary-fixed': '#291800',
        outline: '#717783',
        'primary-container': '#2976c7',
        'on-background': '#1b1c1c',
        background: '#fbf9f8',
        'tertiary-fixed': '#ffddb4',
        'on-secondary-fixed-variant': '#314867',
        'secondary-fixed': '#d4e3ff',
        'surface-container-low': '#f6f3f2',
        'surface-container-high': '#eae8e7',
        'secondary-container': '#c1d9fe',
        'surface-container-highest': '#e4e2e1',
        'on-surface-variant': '#414751',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'outline-variant': '#c1c7d3',
        'on-tertiary-fixed-variant': '#633f00',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#a06900',
        'tertiary-fixed-dim': '#ffb953',
        'surface-bright': '#fbf9f8',
        'secondary-fixed-dim': '#b1c8ed',
        error: '#ba1a1a',
        'primary-fixed': '#d4e3ff',
        'on-secondary-container': '#485e7e',
        'on-secondary-fixed': '#001c39',
        surface: '#fbf9f8',
        'surface-dim': '#dcd9d9',
        'inverse-surface': '#303030',
        'surface-tint': '#0060ac',
        'surface-container': '#f0eded',
        'surface-variant': '#e4e2e1',
        'inverse-on-surface': '#f3f0f0',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
