import { paymentMethodLabel } from '@/constants/paymentMethods'

function formatMoney(n) {
  return `₹${Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function paymentLabel(raw) {
  if (!raw || raw === '—') return '—'
  return paymentMethodLabel(raw)
}

export default function TransactionPrintReport({
  branchName,
  dateRangeLabel,
  generatedBy,
  generatedRole,
  printedAt,
  summary,
  rows,
}) {
  const {
    totalTransactions = 0,
    totalRevenue = 0,
    cashReceived = 0,
    onlineReceived = 0,
    totalPendingDue = 0,
  } = summary ?? {}

  return (
    <div className="transactions-print-area" aria-hidden="true">
      <div className="transactions-print-canvas">
        <header className="transactions-print-header">
          <div>
            <p className="transactions-print-brand">School Kit Manager</p>
            <h1 className="transactions-print-title">Transaction Report</h1>
          </div>
          <div className="transactions-print-meta">
            <p><strong>Branch:</strong> {branchName}</p>
            <p><strong>Period:</strong> {dateRangeLabel}</p>
            <p><strong>Printed on:</strong> {printedAt}</p>
            <p><strong>Generated by:</strong> {generatedBy} ({generatedRole})</p>
          </div>
        </header>

        <section className="transactions-print-summary">
          <p className="transactions-print-tx-count">
            <span className="transactions-print-summary-label">Total Transactions</span>
            <span className="transactions-print-summary-value">{totalTransactions}</span>
          </p>
          <div className="transactions-print-summary-grid">
            <div>
              <span className="transactions-print-summary-label">Total Revenue</span>
              <span className="transactions-print-summary-value">{formatMoney(totalRevenue)}</span>
            </div>
            <div className="transactions-print-summary-cash">
              <span className="transactions-print-summary-label">Cash Received</span>
              <span className="transactions-print-summary-value">{formatMoney(cashReceived)}</span>
            </div>
            <div className="transactions-print-summary-online">
              <span className="transactions-print-summary-label">Online Received</span>
              <span className="transactions-print-summary-value">{formatMoney(onlineReceived)}</span>
            </div>
            <div className="transactions-print-summary-pending">
              <span className="transactions-print-summary-label">Pending</span>
              <span className="transactions-print-summary-value">{formatMoney(totalPendingDue)}</span>
            </div>
          </div>
        </section>

        <table className="transactions-print-table">
          <thead>
            <tr>
              <th className="transactions-print-col-sno">S.No</th>
              <th>Order ID</th>
              <th>Date</th>
              <th>Student Name</th>
              <th>Class</th>
              <th>Payment Method</th>
              <th>Amount</th>
              <th>Status</th>
              <th>Remarks</th>
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 ? (
              <tr>
                <td colSpan={9} className="transactions-print-empty">
                  No transactions match the current filters.
                </td>
              </tr>
            ) : (
              rows.map((row, index) => (
                <tr key={row.id}>
                  <td className="transactions-print-col-sno">{index + 1}</td>
                  <td>{row.orderId}</td>
                  <td>{row.date}</td>
                  <td>{row.studentName}</td>
                  <td>{row.classLabel}</td>
                  <td>{paymentLabel(row.kitType)}</td>
                  <td>{formatMoney(row.amount)}</td>
                  <td>{row.status}</td>
                  <td>{row.remarksFull || row.remarks || '—'}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>

        <footer className="transactions-print-footer">
          <span>Confidential — School Kit Manager</span>
        </footer>
      </div>
    </div>
  )
}
