export const transactionsKpis = {
  revenueToday: 12480,
  ordersToday: 42,
}

export const transactionsRows = [
  {
    id: '1',
    orderId: '#SKM-2024-8842',
    orderedLine: 'Ordered on Mar 12, 2024 • 09:12 AM',
    date: 'Mar 12',
    studentName: 'Arjun Malhotra',
    initials: 'AM',
    initialsClass: 'bg-primary-fixed text-primary',
    classLabel: 'Class 6-A',
    kitType: 'Full Book + Uniform',
    amount: 365,
    status: 'Paid',
  },
  {
    id: '2',
    orderId: '#SKM-2024-8843',
    orderedLine: 'Ordered on Mar 11, 2024 • 11:20 AM',
    date: 'Mar 11',
    studentName: 'Sara Patel',
    initials: 'SP',
    initialsClass: 'bg-tertiary-fixed text-tertiary',
    classLabel: 'Class 4-C',
    kitType: 'Summer Uniform Set',
    amount: 120,
    status: 'Pending',
  },
  {
    id: '3',
    orderId: '#SKM-2024-8844',
    orderedLine: 'Ordered on Mar 11, 2024 • 02:05 PM',
    date: 'Mar 11',
    studentName: 'Rohan Kapoor',
    initials: 'RK',
    initialsClass: 'bg-primary-fixed-dim text-on-primary-fixed',
    classLabel: 'Class 9-B',
    kitType: 'Science Kit (Advanced)',
    amount: 450,
    status: 'Paid',
  },
  {
    id: '4',
    orderId: '#SKM-2024-8845',
    orderedLine: 'Ordered on Mar 10, 2024 • 08:45 AM',
    date: 'Mar 10',
    studentName: 'Isha Sharma',
    initials: 'IS',
    initialsClass: 'bg-outline-variant text-on-surface',
    classLabel: 'Class 2-A',
    kitType: 'Stationery Bundle',
    amount: 85,
    status: 'Partial',
  },
  {
    id: '5',
    orderId: '#SKM-2024-8846',
    orderedLine: 'Ordered on Mar 09, 2024 • 04:30 PM',
    date: 'Mar 09',
    studentName: 'Dev Verma',
    initials: 'DV',
    initialsClass: 'bg-secondary-container text-on-secondary-container',
    classLabel: 'Class 10-A',
    kitType: 'Senior Kit',
    amount: 525,
    status: 'Pending',
  },
]
